### ISSUE TITLE
Second goal for a project isn't taking precedence if there's a past existing goal.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#361] opened 2019-02-28 21:12 UTC
1. I created the primary project "Staging Testing" a few days ago.
2. I created a goal that ran from 2/26 - 2/27, with a final word count of 200/500. (Goal 1)
3. Today, on 2/28, I created a goal that runs from 2/28 - 3/1. Current count was 0/1200. (Goal 2)
4. On the projects page, the goal displayed under this project is still Goal 1.
5. In the word-count updater from the nav, I have it set to update via total, and it's already populated with 200.
6. I tried to update the total word count and saw no effect for either goal.
7. I switched to updating by session instead of total and added 1400 words to my count, and then this change displayed on the stats dashboard for Goal #2. 
8. On the projects page, the goal displayed is now Goal #2, but the progress bar now reflects (Goal 1 word count + Goal 2 word count). Basically, it's showing (200 + 1400) = 1600.
9. If I switch the word-count updater in the nav to update by total, that is also pre-populating 1600.

**Comment by nanojezra** [comment] 2019-02-28 22:30
I just ran into part of this while testing something else and it was very confusing.  There are multiple issues here.

In steps 5 and 9 when updating by total, the number being displayed is the project's total. switching to display the current goal total is trivial, and the current goal name should also be displayed under the project name in the form. The downside will be that users can no longer enter the word count provided by their writing software as the "total"

In step 6, what number did you enter for the total count? If the number didn't change from 200, then there was no number to submit and that would explain 7

Can I please get a screen shot of 8? I am unable to reproduce the display error

**Comment by timhkim** [comment] 2019-02-28 23:23
- Oh, I see what you're saying about the total from the writing software. We toyed with the idea of letting people set a "starting word count" for their goals, and it's kind of reflected when you're creating a new project, so maybe we can address that down the road.
- I can't remember specifically, but I know it was a total word count larger than 200.
- Adding a picture!

![screenshot 2019-02-28 at 3 22 24 pm](https://user-images.githubusercontent.com/39069145/53605584-cd658500-3b6c-11e9-8bf8-1ab65785f72c.png)

**Comment by nanojezra** [comment] 2019-02-28 23:48
yea, that is probably getting the same value as steps 5 and 9

**Comment by timhkim** [comment] 2019-03-05 20:29
Just for clarity's sake; I think we settled on:

- [ ] Switching to display the current goal total rather than project total in the updater
- [ ] The current goal name should also be displayed under the project name in the form.
- [ ] Displaying the current (or, if there's not current, most recent) goal total rather than project total in the project card on the "My Projects" page

I think if we switch to all of this, the only place we're actually showing the project total rather than current goal total is on the Project Details page. Image attached below. I think that's okay for the behaviors we're expecting!

![image](https://user-images.githubusercontent.com/39069145/53835437-4f292a00-3f42-11e9-91f3-21606d546bd5.png)

**Comment by nanojezra** [comment] 2019-03-12 22:04
How do you feel about replacing the "total" option in the select, with "project total" and "goal total"?

The resulting counting options would then be:
project total
goal total
this session

Also, I found a bug in the code that was prohibiting the unit type (words, hours, etc) from being displayed in the select.

**Comment by timhkim** [comment] 2019-03-12 22:07
I think given your great suggestion for putting in the goal name, it makes sense to limit to "total" and "this session". I'm worried about confusing people, I guess? If we see a lot of requests for "project total" down the road, it seems like something we can add, but I'd be surprised.

Oh, good bug find!

**Comment by nanojezra** [comment] 2019-03-13 19:32
On staging right now, you can see what it would look like with 'project total words', 'goal total words', and 'words this session' options.

**Comment by timhkim** [comment] 2019-03-14 15:23
Ooh, thanks for letting me take a look at that!

I think for now, it'll require more explanation to people than it's worth. I can imagine introducing this down the road if people ask for it, but I think it might be an overcomplication at the moment.

**Comment by nanojezra** [comment] 2019-03-14 16:29
I will modify the code to only show Project Total when user.name = 'jezra', because I as a user absolutely need to enter my count based on the project's total as that is how I get the wordcount from my text editor.

**Comment by timhkim** [comment] 2019-03-14 16:46
Sorry; just to make sure I'm understanding correctly!

For users like you, you're envisioning difficulty when you create a second goal for a project, and you want to keep updating the total that your text editor is giving you? So in that case, when you're updating the project total, is your goal tracker subtracting the beginning word count from your new project total to track this second goal?

**Comment by nanojezra** [comment] 2019-03-14 19:01
yes. the computer does the math so the user doesn't have to

**Comment by nanodave** [comment] 2019-10-17 15:43
I'd like to close this to get our tickets out of public view. What's the status?

**Closed** 2022-10-27 16:44 UTC
Labels: bug
